export const FETCH_RANDOM_BIOS_LOADING = 'FETCH_RANDOM_BIOS_LOADING';
export const FETCH_RANDOM_BIOS_SUCCESS = 'FETCH_RANDOM_BIOS_SUCCESS';
export const FETCH_RANDOM_BIOS_ERROR = 'FETCH_RANDOM_BIOS_ERROR';
